# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'video_page.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 578)
        MainWindow.setMinimumSize(QtCore.QSize(813, 578))
        MainWindow.setMaximumSize(QtCore.QSize(813, 578))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(600, 160, 201, 197))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.angryLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.angryLabel.setFont(font)
        self.angryLabel.setObjectName("angryLabel")
        self.verticalLayout.addWidget(self.angryLabel)
        self.disgustLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.disgustLabel.setFont(font)
        self.disgustLabel.setObjectName("disgustLabel")
        self.verticalLayout.addWidget(self.disgustLabel)
        self.fearLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.fearLabel.setFont(font)
        self.fearLabel.setObjectName("fearLabel")
        self.verticalLayout.addWidget(self.fearLabel)
        self.happyLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.happyLabel.setFont(font)
        self.happyLabel.setObjectName("happyLabel")
        self.verticalLayout.addWidget(self.happyLabel)
        self.sadLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.sadLabel.setFont(font)
        self.sadLabel.setObjectName("sadLabel")
        self.verticalLayout.addWidget(self.sadLabel)
        self.surpriseLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.surpriseLabel.setFont(font)
        self.surpriseLabel.setObjectName("surpriseLabel")
        self.verticalLayout.addWidget(self.surpriseLabel)
        self.neutralLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(15)
        self.neutralLabel.setFont(font)
        self.neutralLabel.setObjectName("neutralLabel")
        self.verticalLayout.addWidget(self.neutralLabel)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(12, 12, 791, 111))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.titleLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.titleLabel.setFont(font)
        self.titleLabel.setObjectName("titleLabel")
        self.horizontalLayout.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.copyrightLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.copyrightLabel.setFont(font)
        self.copyrightLabel.setObjectName("copyrightLabel")
        self.horizontalLayout.addWidget(self.copyrightLabel)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.useCameraButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(20)
        self.useCameraButton.setFont(font)
        self.useCameraButton.setObjectName("useCameraButton")
        self.horizontalLayout_2.addWidget(self.useCameraButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.useImageButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(20)
        self.useImageButton.setFont(font)
        self.useImageButton.setObjectName("useImageButton")
        self.horizontalLayout_2.addWidget(self.useImageButton)
        self.useVideoButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(20)
        self.useVideoButton.setFont(font)
        self.useVideoButton.setObjectName("useVideoButton")
        self.horizontalLayout_2.addWidget(self.useVideoButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        self.videoLabel.setGeometry(QtCore.QRect(10, 140, 561, 371))
        font = QtGui.QFont()
        font.setFamily("PingFang SC")
        font.setPointSize(30)
        self.videoLabel.setFont(font)
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(610, 460, 185, 60))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/img/logo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 813, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "人脸表情识别系统V1.0"))
        self.angryLabel.setText(_translate("MainWindow", "生气：0.00%"))
        self.disgustLabel.setText(_translate("MainWindow", "厌恶：0.00%"))
        self.fearLabel.setText(_translate("MainWindow", "害怕：0.00%"))
        self.happyLabel.setText(_translate("MainWindow", "高兴：0.00%"))
        self.sadLabel.setText(_translate("MainWindow", "悲伤：0.00%"))
        self.surpriseLabel.setText(_translate("MainWindow", "惊讶：0.00%"))
        self.neutralLabel.setText(_translate("MainWindow", "中立：0.00%"))
        self.titleLabel.setText(_translate("MainWindow", "人脸表情识别系统V1.0"))
        self.copyrightLabel.setText(_translate("MainWindow", "爱编程的小芯 2022.4"))
        self.useCameraButton.setText(_translate("MainWindow", "使用摄像头"))
        self.useImageButton.setText(_translate("MainWindow", "打开图像文件"))
        self.useVideoButton.setText(_translate("MainWindow", "打开视频文件"))
        self.videoLabel.setText(_translate("MainWindow", "图像/视频画面"))

